name = "Hodge"
uuid = "3c44080d-357b-4062-ad7b-6cab49ad4f79"
authors = ["Iago Leal de Freitas"]
version = "0.0.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
julia = "1.4"
